services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: reviews

  mysql:
    image: mysql:8.0
    volumes:
      - reviews_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: reviews

volumes:
  reviews_data:
